import { Category, Reel, Show, UserProgress } from '@/lib/types';

export const categories: Category[] = [
  { id: 'popular', label: 'Popular' },
  { id: 'top', label: 'Top' },
  { id: 'new', label: 'New' },
  { id: 'male', label: 'Male' },
  { id: 'female', label: 'Female' },
  { id: 'regional', label: 'Regional' },
  { id: 'dubbed', label: 'Dubbed' },
];

export const shows: Show[] = [
  {
    id: 's1',
    title: 'Neon Verdict',
    language: 'English',
    genres: ['Thriller', 'Drama'],
    views: '3.1M',
    posterUrl: 'https://picsum.photos/400/600?random=11',
    backdropUrl: 'https://picsum.photos/900/600?random=21',
    isNew: true,
    tagLine: 'Power Games',
    about: 'A young attorney enters a televised courtroom league where verdicts are decided by public votes.',
    rating: 'U/A 16+',
    releaseCountdown: 'LIVE IN 02:28:35',
    isSeries: true,
  },
  {
    id: 's2',
    title: 'Crimson Alley',
    language: 'Urdu',
    genres: ['Action', 'Mystery'],
    views: '980K',
    posterUrl: 'https://picsum.photos/400/600?random=12',
    backdropUrl: 'https://picsum.photos/900/600?random=22',
    tagLine: 'Street Justice',
    about: 'An undercover rider tracks a hidden syndicate while balancing loyalty and revenge.',
    rating: 'U/A 13+',
    isSeries: false,
  },
  {
    id: 's3',
    title: 'Paper Moon Hotel',
    language: 'Hindi',
    genres: ['Romance', 'Drama'],
    views: '1.6M',
    posterUrl: 'https://picsum.photos/400/600?random=13',
    backdropUrl: 'https://picsum.photos/900/600?random=23',
    isNew: true,
    tagLine: 'Second Chances',
    about: 'Two strangers inherit the same vintage hotel and discover old stories stitched into every room.',
    rating: 'U',
    releaseCountdown: 'Tomorrow',
    isSeries: true,
  },
  {
    id: 's4',
    title: 'Quantum Dhol',
    language: 'Punjabi',
    genres: ['Comedy', 'Action'],
    views: '760K',
    posterUrl: 'https://picsum.photos/400/600?random=14',
    backdropUrl: 'https://picsum.photos/900/600?random=24',
    tagLine: 'Beat Drop',
    about: 'A failing wedding band discovers a beat that can briefly rewind time.',
    rating: 'U/A 13+',
    isSeries: false,
  },
  {
    id: 's5',
    title: 'Velvet Frontier',
    language: 'Tamil',
    genres: ['Drama', 'Mystery'],
    views: '2.4M',
    posterUrl: 'https://picsum.photos/400/600?random=15',
    backdropUrl: 'https://picsum.photos/900/600?random=25',
    tagLine: 'Royal Secrets',
    about: 'A palace archivist uncovers a prophecy that ties her bloodline to the kingdom collapse.',
    rating: 'U/A 16+',
    isSeries: true,
  },
  {
    id: 's6',
    title: 'Midnight Local',
    language: 'Bengali',
    genres: ['Thriller', 'Mystery'],
    views: '1.2M',
    posterUrl: 'https://picsum.photos/400/600?random=16',
    backdropUrl: 'https://picsum.photos/900/600?random=26',
    isNew: true,
    tagLine: 'Last Ride',
    about: 'Every night a metro train appears on a closed platform with passengers from the future.',
    rating: 'U/A 16+',
    releaseCountdown: 'LIVE IN 05:11:20',
    isSeries: false,
  }
];

export const reels: Reel[] = Array.from({ length: 6 }).map((_, idx) => ({
  id: `r${idx + 1}`,
  showId: idx % 2 ? 's1' : 's3',
  title: `Episode ${idx + 1}: Echoes`,
  duration: `${14 + idx} min`,
}));

export const progressSeed: UserProgress[] = [
  { showId: 's1', progress: 0.42, leftLabel: '1 hr 37 min left' },
  { showId: 's3', progress: 0.65, leftLabel: '42 min left' },
  { showId: 's6', progress: 0.2, leftLabel: '2 hr 06 min left' },
];
